### ISSUE TITLE
yarn install 之后报错

### ISSUE THREAD

**Issue by sophychow** [xiaolai/everyone-can-use-english#105]
按照命令执行下来后，进入 'everyone-can-use-english/enjoy' 目录后，执行 yarn Install，出现以下错误，有谁遇到过这种情况吗？谢谢
![image](https://github.com/xiaolai/everyone-can-use-english/assets/11385675/7635ec50-2160-476b-8566-e11b42da0c72)
![image](https://github.com/xiaolai/everyone-can-use-english/assets/11385675/0966ade8-0446-4b0e-93bb-9c4a5861faee)

**Comment by viquu** [comment]
I have similar problem. When execute 'yarn install'

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by an-lee** [comment]
不需要进入 /enjoy 目录，直接在项目根目录 `yarn install`

**Comment by viquu** [comment]
> 不需要进入 /enjoy 目录，直接在项目根目录 `yarn install`

就是在根目录执行的。 然后我又去你说的enjoy目录试了一下，同样的错误。

**Comment by jagerrrrr** [comment]
类似的错误，我这里也是这样

**Comment by sophychow** [comment]
> 不需要进入 /enjoy 目录，直接在项目根目录 `yarn install`

在根目录或者/enjoy目录执行yarn install也是同样的问题

**Comment by zytbft** [comment]
macbook air m2 ，macOS Sonoma 14.2.1，执行yarn install，遇到了如下错误，如果方便，请帮忙看看

➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide next (pf50d7), requested by next-themes.
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (p50636), requested by vite-plugin-static-copy.
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (pe5759), requested by @vitejs/plugin-react.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 344ms
➤ YN0000: ┌ Link step
➤ YN0007: │ electron@npm:28.1.3 must be built because it never has been before or the last one failed
➤ YN0009: │ electron@npm:28.1.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/zj/8t4r3tkd6_34px_278db72g00000gn/T/xfs-2c6fba8e/build.log)
➤ YN0009: │ electron@npm:28.1.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/zj/8t4r3tkd6_34px_278db72g00000gn/T/xfs-4d882d47/build.log)
➤ YN0000: └ Completed in 11s 65ms
➤ YN0000: · Failed with errors in 11s 534ms

**Comment by an-lee** [comment]
试试

```
corepack enable
```

之后再 

```
yarn install
```

**Comment by q1114707486** [comment]
PS F:\pc\code\learn\github\everyone-can-use-english\enjoy> yarn install
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 246ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide next (pf50d7), requested by next-themes.
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (p50636), requested by vite-plugin-static-copy.
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (pe5759), requested by @vitejs/plugin-react.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 756ms
➤ YN0000: ┌ Link step
➤ YN0007: │ electron@npm:28.1.2 must be built because it never has been before or the last one failed
➤ YN0009: │ electron@npm:28.1.2 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\admin\AppData\Local\Temp\xfs-af5b2be2\build.log)
➤ YN0000: └ Completed in 11s 315ms
➤ YN0000: · Failed with errors in 12s 405ms  这个报错怎么解决 @an-lee

**Comment by an-lee** [comment]
每个人的开发环境都不一样，每个系统也都不一样（我自己在用 Linux），所以开发环境的问题大部分只能靠自己 Google 解决。

如果不是要贡献代码，没必要折腾这个，直接下载打包好的软件使用就好了。

**Comment by sophychow** [comment]
> PS F:\pc\code\learn\github\everyone-can-use-english\enjoy> yarn install ➤ YN0000: · Yarn 4.0.2 ➤ YN0000: ┌ Resolution step ➤ YN0000: └ Completed in 0s 246ms ➤ YN0000: ┌ Post-resolution validation ➤ YN0002: │ enjoy@workspace:enjoy doesn't provide next (pf50d7), requested by next-themes. ➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (p50636), requested by vite-plugin-static-copy. ➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (pe5759), requested by @vitejs/plugin-react. ➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements for details, where is the six-letter p-prefixed code. ➤ YN0000: └ Completed ➤ YN0000: ┌ Fetch step ➤ YN0000: └ Completed in 0s 756ms ➤ YN0000: ┌ Link step ➤ YN0007: │ electron@npm:28.1.2 must be built because it never has been before or the last one failed ➤ YN0009: │ electron@npm:28.1.2 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\admin\AppData\Local\Temp\xfs-af5b2be2\build.log) ➤ YN0000: └ Completed in 11s 315ms ➤ YN0000: · Failed with errors in 12s 405ms 这个报错怎么解决 @an-lee

这段话的意思是提示电脑需要安装electron，进入enjoy目录去安装electron，yarn add --dev electron，再返回到根目录everyone-can-use-english一次执行：
`yarn install`
`yarn start:enjoy`

**Comment by sophychow** [comment]
这个问题已经解决，总结一下：
1、本地环境需要：node版本大于18.0.0（安装方式多种，可以google或者百度，我用的是nvm）
2、本地环境需要：electron  (electron官网https://www.electronjs.org/zh/)
3、增强包管理命令：corepack enable--@an-lee提供的这个命令在yarn install或者yarn -v之前用一下，有效避免了yarn命令失效的情况

谢谢@an-lee的解答以及各位提供的现象和方向

**Comment by Ninohana** [comment]
`YN0009: │ electron@npm:28.1.2 couldn't be built successfully`

这个错误去看日志，有可能是没有Python环境和make、cc等环境
